Sprint 2
kami16ru/middle.messenger.praktikum.yandex pull request #2
Opened 2022-08-17 00:02 UTC by kami16ru

2022-08-17 13:54 UTC, podlovchenko requested changes
Привет) Спасибо за проделанную работу, есть несколько замечаний
1. Нет класса HTTPTransport
2. Очень много мест, где используется ts-ignore, это плохая практика (как и типизация через any), так как теряются все преимущества типизации
3. Было бы здорово почистить проект от закомментированного кода
4. На нетлифае старая версия

Жду правок)

2022-08-17 13:54 UTC, podlovchenko commented on .editorconfig
> +trim_trailing_whitespace = false
В проекте в некоторых файлах есть ошибка EOF
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-08-17 13:54 UTC, podlovchenko commented on package.json
> +    "@parcel/transformer-typescript-tsc": "^2.7.0",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-08-17 13:54 UTC, podlovchenko commented on package.json
>      "express": "^4.17.3",
В evDependencies указывается то, что необходимо при сборке, в dependencies то, что необходимо при просмотре приложения (express и uuid)

2022-08-17 13:54 UTC, podlovchenko commented on src/components/ui/button/index.ts
> +export default new Button({
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая [статья](https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/) на эту тему

2022-08-17 13:54 UTC, podlovchenko commented on src/components/ui/button/index.ts
> +class Button extends Component {
Было бы здорово сделать класс Block [дженериком](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников
Пример:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-08-17 13:54 UTC, podlovchenko commented on src/components/ui/nav/nav-drawer/index.ts
> +      // navDrawer.style.width = '250px';
Закомментированный код лучше не оставляять в проекте

2022-08-17 13:54 UTC, podlovchenko commented on src/layouts/auth/index.ts
> +  props: {}
Зачем передавать пустой объект?

2022-08-17 13:54 UTC, podlovchenko commented on src/lib/dom/types.ts
> +  _element: Element
Для приватных свойств не хватает модификатора private

2022-08-17 13:54 UTC, podlovchenko commented on tsconfig.json
> +    "strictNullChecks": false,
По заданию должны быть настройки
```
"noImplicitAny": true,

"noUnusedLocals": true,

"noUnusedParameters": true,

"sourceMap": true,

"strictNullChecks": true
```

2022-08-17 13:54 UTC, podlovchenko commented on src/modules/error/pages/404/index.ts
> +import template from './template.hbs'
Нужно добавить файл hbs.d.ts
```
declare module '*.hbs' {
  const content: NewableFunction
  export default content
}
```

2022-08-17 13:55 UTC, podlovchenko commented on src/modules/error/pages/404/index.ts
> +import template from './template.hbs'
Увидела, что такой файл есть, но в tsconfig указан путь `./src/**`, а файл лежит в `./`

2022-08-17 14:07 UTC, kami16ru commented on package.json
> +    "@parcel/transformer-typescript-tsc": "^2.7.0",
package-lock у меня в репозитории а не в игноре. Как раз таки чтобы избежать таких кейсов, в официальной документации npm рекомендуется держать package-lock в git

2022-08-17 14:11 UTC, kami16ru commented on src/modules/error/pages/404/index.ts
> +import template from './template.hbs'
Спасибо)

2022-08-18 00:35 UTC, kami16ru commented on src/components/ui/button/index.ts
> +export default new Button({
Я подумал на эту тему. В моем случае я экспортирую инстанс а не класс. Классы принято называть с заглавной буквы. Инстансы с маленькой. Однако я выбрал заглавную букву для компонентов, чтобы подчеркнуть что это компоненты.

Потом называть инстансы разными именами нормальная практика.

Я еще не решил, оставлять мне такую реализацию и хранить в инстансе массив элементов, либо создавать новые инстансы для каждого элемента. В каждом подходе есть свой плюс. Если работать с инстансами, то их будет меньше в приложении, легче искать, и даже легче будет искать и посчитать созданные элементы.

Если экспортировать класс и создавать инстансы на страницах, в этом тоже есть определенно плюс. Если для каждого элемента создавать инстанс, легче проследить за их инициализацией, проще их описать, и можно использовать плюсы наследования классов.

Скорее всего я перейду к экспортированию классов, и тогда обязательно послушаю твой совет и воспользуюсь деструктаризацией. Спасибо тебе!

2022-08-18 00:39 UTC, kami16ru commented on .editorconfig
> +trim_trailing_whitespace = false
Вот странно, я ubuntu использую. Думал тут само такие вещи проставляются и данная проблема есть на винде только

2022-08-19 18:38 UTC, podlovchenko approved these changes
Работу принимаю, хороших выходных)

2022-08-19 18:38 UTC, podlovchenko commented on package.json
>      "start": "npm run parcel-dev & node server.js",
Почему не
```suggestion
    "start": "npm run build & node server.js",
```
?

2022-08-19 18:38 UTC, podlovchenko commented on src/lib/http/types.ts
> +export enum METHODS {
enum обычно именуется в PascalCase

2022-08-19 20:23 UTC, merged